version: '3.9'

services:
  backend:
    image: backend
    build:
      context: ./backend
    ports:
      - "8080:8080" 

  frontend:
    image: frontend
    build:
      context: ./frontend
    ports:
      - "5173:80"

